#!/bin/bash
# voidnsrun setup script

repokeys_dir="/var/db/xbps/keys"

# Check if base-voidstrap is installed on glibc container
function checkstrap {
    xbps-query -r /glibc -m | grep base-voidstrap
    exitstatus=$?
        
    if [ $exitstatus = 0 ]; then
        strapinstalled=1
    else
        strapinstalled=0
    fi
}

# Get Void main mirror in use and adapt it to use glibc instead of musl.
    function get_target_repo {
        if [ ! -d /etc/xbps.d/00-repository-main.conf ]; then
            mainrepofile="/usr/share/xbps.d/00-repository-main.conf"
        else
            mainrepofile="/etc/xbps.d/00-repository-main.conf"
        fi

        cat $mainrepofile | cut -d"=" -f2 | sed 's|/musl||g'
}

# Get Cereus main mirror in use and adapt it to use x86_64 instead of x86_64-musl

    function get_cereus_repo {
        if [ ! -d "/etc/xbps.d/10-cereus-extra.conf" ]; then
            cereus_extra="/usr/share/xbps.d/10-cereus-extra.conf"
        else
            cereus_extra="/etc/xbps.d/10-cereus-extra.conf"
        fi

        cat $cereus_extra | cut -d"=" -f2 | sed 's|x86_64-musl|x86_64|g'
}

# Create the base glibc container
    function create_container { 
        XBPS_ARCH=x86_64 xbps-install --repository=$(get_target_repo) -r /glibc -Sy base-voidstrap
}

# Checks if /glibc container path exists, and if it has installed the base-voidstrap package. 
# Otherwise, it will create the path and configure the container.

    if [ ! -d "/glibc" ]; then
        echo "==> Creating container path
"
        mkdir -p /glibc/${repokeys_dir}
        echo "==>Copying repositories keys...
"
        cp ${repokeys_dir}/*.plist /glibc/${repokeys_dir}/
        echo "==> Creating glibc container, this will take a bit...
"
        create_container
    else
        checkstrap
        if [ $strapinstalled = 0 ]; then
        echo "==> Copying repositories keys...
"
        mkdir -p /glibc/${repokeys_dir}
        cp ${repokeys_dir}/*.plist /glibc/${repokeys_dir}/
        echo "==> Creating glibc container, this will take a bit...
"
            create_container
        fi
    fi

# Install voidnsundo in container and add cereus-extra repository
echo "==> Configuring extra repository and voidnsundo
"
voidnsrun -r /glibc xbps-install -Syfv --repository=$(get_cereus_repo) voidnsundo cereus-repo-extra
