==> IMPORTANT NOTE:
LPKG is a low-level package manager. This means that it will not install automatically dependencies.
Instead of that, you will have to look yourself for them.

At Cereus Linux Team we'll provide some packages dependencies, but this may be outdated over the time.
You can find our list at: https://github.com/CereusLinuxProject/lpkg-list

==> WARNING:
* You MUST NOT install a package twice in LPKG and XBPS, this will cause conflicts and probably BREAK YOUR SYSTEM.
* To avoid conflicts, when removing LPKG it will automatically remove all your LPKG packages.



